In [1]:
conda install numpy

Channels:
 - defaults
Platform: osx-arm64
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
#numpy array

In [3]:
my_list = [10,20,30,40]

In [4]:
type(my_list)

list

In [5]:
np.array(my_list)

array([10, 20, 30, 40])

In [6]:
my_numpy_array = np.array(my_list)

In [7]:
type(my_numpy_array)

numpy.ndarray

In [8]:
my_numpy_array

array([10, 20, 30, 40])

In [9]:
my_numpy_array[0]

10

In [10]:
my_numpy_array[-1]

40

In [11]:
my_numpy_array[0] = 100

In [12]:
my_numpy_array

array([100,  20,  30,  40])